source 'https://rubygems.org'
gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'paperclip'
gem 'haml'
gem 'simple_form'
gem 'mysql'
gem 'capistrano'
gem 'capistrano-bundler'
gem 'capistrano-rails'
gem 'inherited_resources'
gem 'protected_attributes'
gem 'twilio-ruby'